import type { Metadata } from 'next';
import Navbar from './components/Navbar/Navbar';
import { robotoMono, rubik } from './fonts';
import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

console.log(rubik);

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en' className={`${rubik.variable} ${robotoMono.variable}`}>
      <body>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
